---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: 
        - apache2
        - net-tools
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

