---

- hosts: all
  become: true
  tasks:

  - name: remove net-tools and apache2 package
    apt:
      name: 
         - apache2
         - net-tools
      state: absent
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
