---

- hosts: all
  become: true
  tasks:

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent
  - name: install net-tools package
    apt:
      name: net-tools
      state: absent
  - name: update repository index
    apt: 
       update_cache: yes
