---

- hosts: all
  become: true
  pre_tasks:

  - name: remove net-tools and apache2 package
    tags: centos,db
    apt:
      name: 
         - apache2
         - net-tools
      state: absent
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:
 
  - name: install net-tools package
    tags: apache, apache
    apt: 
      name: 
        - net-tools
        - apache2
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
