---

- hosts: web_server
  become: true
  tasks:

  - name: install apache and php for ubuntu servers
    tags: apache,ubuntu,php
    apt:
      name:
        - apache2
        - php
      state: latest
  - name: copy thanh.html file for website
    tags: apache, apache2,php
    copy: 
       src: thanh.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644

- hosts: web_server
  become: true
  tasks:

  - name: install ubzip
    apt:
      name: unzip
  - name: install terraform
    unarchive: 
      src: ...
      dest: /usr/local/bin
      remote_src: yes
      mote: 0755
      owner: root
      group: root
