---

- hosts: web_server
  become: true
  tasks:

  - name: install apache and php for ubuntu servers
    tags: apache,ubuntu,php
    apt:
      name:
        - apache2
        - php
      state: latest

  - name: start apache (ubuntu)
    tags: apache,ubuntu
    service:
      name: apache2
      state: started
      enabled: yes

  - name: change mail
    tags: apache,ubuntu
    lineinfile:
         path: /etc/apache2/apache2.conf
         regexp: '^ServerAdmin'
         line: ServerAdmin somebody@somewhere.net
    register: apache2

  - name: restart apache2 
    tags: apache,ubuntu
    service:
        name: apache2
        state: restarted
    when: apache2.changed

  - name: copy thanh.html file for website
    tags: apache, apache2,php
    copy: 
       src: thanh.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
