- name: install httpd package (CentOS)
  tags: apache,centos,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start and enable httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: latest
  when: ansible_distribution == "CentOS"

- name: install apache2 package (Ubuntu)
  tags: apache,apache2,ubuntu
  dnf:
    name:
      - apache2
      - libaphache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: start apache (ubuntu)
  tags: apache,ubuntu
  service:
     name: apache2
     state: started
     enabled: yes

- name: change mail
  tags: apache,ubuntu
  lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
  register: apache2

- name: restart apache2
  tags: apache,ubuntu
  service:
     name: apache2
     state: restarted
  when: apache2.changed

- name: copy thanh.html file for website
  tags: apache, apache2,php
  copy:
    src: thanh.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
